# Generated by Django 6.0.7 on 2026-07-31 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_rename_quality_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('succeeded', 'Başarılı'), ('failed', 'Başarısız'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], default='pending', max_length=20)),
                ('method', models.CharField(blank=True, choices=[('credit_card', 'Kredi Kartı'), ('debit_card', 'Banka Kartı'), ('wallet', 'Cüzdan'), ('bank_transfer', 'Havale/EFT'), ('cash_on_delivery', 'Kapıda Ödeme')], max_length=30, null=True)),
                ('provider', models.CharField(blank=True, max_length=50, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
